---
title: "Parse training sets and get URLs"
output: html_notebook
---

```{r message=FALSE}
library(tidyverse)
library(paws)
```


```{r}
info_cols <-
  c(
    "Image_Metadata_MasterIndex",
    "ImageNumber",
    "ObjectNumber",
    "Class",
    "Image_ImageQuality_LocalFocusScore_OrigDNA_5"
  )
```


```{r}
s3 <- paws::s3()
MyTrainingSet_4channel <- 
  read_csv(
    s3$get_object(Bucket = "jump-cellpainting", 
                  Key = "projects/2019_07_11_JUMP-CP-pilots/workspace/qc_postprocessing/debris_annotations/MyTrainingSet_4channel.csv")$Body
  ) %>% select(all_of(info_cols), matches("UserAnnotation_"))

MyTrainingSet_5channel <- 
  read_csv(
    s3$get_object(Bucket = "jump-cellpainting", 
                  Key = "projects/2019_07_11_JUMP-CP-pilots/workspace/qc_postprocessing/debris_annotations/MyTrainingSet_5channel.csv")$Body
  ) %>% select(all_of(info_cols), matches("UserAnnotation_"))

MyTrainingSet_6channel <- 
  read_csv(
    s3$get_object(Bucket = "jump-cellpainting", 
                  Key = "projects/2019_07_11_JUMP-CP-pilots/workspace/qc_postprocessing/debris_annotations/MyTrainingSet_6channel.csv")$Body
  ) %>% select(all_of(info_cols), matches("UserAnnotation_"))

```

```{r}
con <-
  DBI::dbConnect(
    RSQLite::SQLite(),
    "~/work/projects/2019_07_11_JUMP-CP/workspace/qc_postprocessing/debris_annotations/DavidPearlQCFixed_6channel_exclude_nd2_Actin_DNA_ER_Golgi_Mito_RNA.sqlite"
  )
qc <- tbl(con, "DavidPearlQCFixed_6channel")
MyTrainingSet_6channel_map <-
  qc %>% select(Image_Metadata_MasterIndex, matches("URL|Path"), Image_ImageQuality_LocalFocusScore_OrigDNA_5) %>% collect()


con <-
  DBI::dbConnect(
    RSQLite::SQLite(),
    "~/work/projects/2019_07_11_JUMP-CP/workspace/qc_postprocessing/debris_annotations/DavidPearlQCFixed_exclude_nd2_AGP_DNA_ER_Mito_RNA.sqlite"
  )
qc <- tbl(con, "DavidPearlQCFixed")
MyTrainingSet_5channel_map <-
  qc %>% select(Image_Metadata_MasterIndex, matches("URL|Path"), Image_ImageQuality_LocalFocusScore_OrigDNA_5) %>% collect()

con <-
  DBI::dbConnect(
    RSQLite::SQLite(),
    "~/work/projects/2019_07_11_JUMP-CP/workspace/qc_postprocessing/debris_annotations/DavidPearlQCFixed_only_nd2_AGP_DNA_ER_Mito.sqlite"
  )
qc <- tbl(con, "DavidPearlQCFixed")
MyTrainingSet_4channel_map <-
  qc %>% select(Image_Metadata_MasterIndex, matches("URL|PathName|FileName"), Image_ImageQuality_LocalFocusScore_OrigDNA_5) %>% collect()

```

```{r}
check_map <- function(df) all(df$Image_ImageQuality_LocalFocusScore_OrigDNA_5.x == df$Image_ImageQuality_LocalFocusScore_OrigDNA_5.y)
MyTrainingSet_4channel_urls <- 
  inner_join(MyTrainingSet_4channel, MyTrainingSet_4channel_map, by = c("Image_Metadata_MasterIndex"))
check_map(MyTrainingSet_4channel_urls)

MyTrainingSet_5channel_urls <- 
  inner_join(MyTrainingSet_5channel, MyTrainingSet_5channel_map, by = c("Image_Metadata_MasterIndex"))
check_map(MyTrainingSet_5channel_urls)

MyTrainingSet_6channel_urls <- 
  inner_join(MyTrainingSet_6channel, MyTrainingSet_6channel_map, by = c("Image_Metadata_MasterIndex"))
check_map(MyTrainingSet_6channel_urls)
```
```{r}
MyTrainingSet_4channel_urls %>% write_csv("~/work/projects/2019_07_11_JUMP-CP/workspace/qc_postprocessing/debris_annotations//MyTrainingSet_4channel_urls.csv")
MyTrainingSet_5channel_urls %>% write_csv("~/work/projects/2019_07_11_JUMP-CP/workspace/qc_postprocessing/debris_annotations//MyTrainingSet_5channel_urls.csv")
MyTrainingSet_6channel_urls %>% write_csv("~/work/projects/2019_07_11_JUMP-CP/workspace/qc_postprocessing/debris_annotations//MyTrainingSet_6channel_urls.csv")
```

